// New server code with event loop

// Pseudo code:
// while running:
//    want_read  = [...]  # socket fds
//    want_write = [...]  # socket fds
//    can_read, can_write = wait_for_readiness(want_read, want_write)
//    for fd in can_read:
//      data = read_nb(fd)  # Non blocking. Only consume from buffer
//      handle_data(fd, data)  # Application logic without IO
//    for fd in can_write:
//      data = pending_data(fd)
//      n = write_nb(fd, data)
//      data_written(fd, n)

#include <vector>
#include <cstdint>

// Each Conn represents one client connection
typedef struct Conn {
  int fd = -1;

  // shows the intention
  bool want_read = false;
  bool want_write = false;
  bool want_close = false;

  // buffered input and output
  std::vector<uint8_t> incoming; // data to be parsed
  std::vector<uint8_t> outgoing; // responses generated by appl
}Conn;
